auctions/urls.py
from django.urls import path

from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("categories", views.categories, name="categories"),
    path("categories/<str:category>", views.categories, name="subCategories"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("create", views.create, name="create"),
    path("listing/<str:listing_id>/<str:title>", views.listing, name="listing"),
    path("watchlistadd/<str:listing_id>",views.watchlist, name="watchlistAdd"),
    path("bid/<str:listing_id>", views.bid, name="bid"),
    path("close/<str:listing_id>", views.close, name="close"),
    path("comment/<str:listing_id>",views.comment, name="comment")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

mail/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    # API Routes
    path("emails", views.compose, name="compose"),
    path("emails/<int:email_id>", views.email, name="email"),
    path("emails/<str:mailbox>", views.mailbox, name="mailbox"),
]

project3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mail.urls'))
]

auctions/models.py
from select import select
from ssl import Options
from statistics import mode
from django.contrib.auth.models import AbstractUser
from django.db import models

categories = [("Electronics","Electronics"), ("Collectibles & Art","Collectibles & Art"), 
("Home & Garden","Home & Garden"), ("Clothing, Shoes & Accessories","Clothing, Shoes & Accessories"), 
("Toys & Hobbies","Toys & Hobbies"), ("Sporting Goods","Sporting Goods"), ("Books, Movies & Music","Books, Movies & Music"), 
("Health & Beauty","Health & Beauty"), ("Business & Industrial","Business & Industrial"), ("Baby Essentials","Baby Essentials"), 
("Pet Supplies","Pet Supplies")]

class User(AbstractUser):
    pass


class Listings(models.Model):
    title = models.CharField(max_length=64)
    imageImg = models.ImageField(blank = True, null=True)
    category = models.CharField(blank = True, max_length=64, choices=categories)
    createDate = models.DateTimeField(auto_now_add=True)
    description = models.CharField(max_length=1024)
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    closed = models.BooleanField(blank = True, null=True)

    def __str__(self):
        return f"{self.title}"



class Bids(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listings, on_delete=models.CASCADE)
    bid = models.DecimalField(decimal_places=2, max_digits=6)

    def __str__(self):
        return f"User: {self.user} Listing:{self.listing} Bid:{self.bid}"

class Comments(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    listing_id = models.ForeignKey(Listings, on_delete=models.CASCADE)
    comment = models.CharField(max_length=1024)

    def __str__(self):
        return f"User: {self.user_id} Listing:{self.listing_id}"

class Watchlist(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    listing_id = models.ForeignKey(Listings, on_delete=models.CASCADE)

    def __str__(self):
        return f"User: {self.user_id} Listing: {self.listing_id}"

auctions/forms.py
from django import forms
from .models import Comments, Listings, Bids

class ListingForm(forms.ModelForm):
    class Meta:
        model = Listings
        fields = ('title', 'imageImg', 'category', 'description')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'category':forms.Select(attrs={'class': 'form-control'}),
            'imageImg': forms.FileInput(attrs={'class': 'form-control-file'})
        }
        labels = {
            'imageImg': 'Image(optional):',
            'category': 'Category(optional):'
        }

class BidForm(forms.ModelForm):
    class Meta:
        model = Bids
        fields = ('bid',)
        widgets = {
            'bid': forms.NumberInput(attrs={'class': 'form-control bid', 'placeholder': 'Bid' })
        }
        labels = {
            'bid':''
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('comment',)
        widgets = {
            'comment': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Comment'})
        }
        labels = {
            'comment':''
        }

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import sys
from .models import Bids, User, Listings, Watchlist, Comments
from .forms import ListingForm, BidForm, CommentForm
from django.db.models.aggregates import Max
from .util import currency

def index(request):
    listings = Listings.objects.all().filter(closed=None)
    return render(request, "auctions/index.html", {
        'listings': listings,
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")

@login_required
def create(request):
    if request.method == "POST":
        lform = ListingForm(request.POST, request.FILES)
        bform = BidForm(request.POST)
        if lform.is_valid() and bform.is_valid():
            listing = lform.save(commit=False)
            listing.seller = request.user
            listing.save()
            bid = bform.save(commit=False)
            bid.user = request.user
            bid.listing = listing
            bid.save()
        return redirect("index")
    else:
        listingForm = ListingForm()
        bidForm = BidForm()
        return render(request, "auctions/create.html", {
            'lform':listingForm,
            'bform':bidForm
        })

def listing(request, listing_id, title):
    listing = Listings.objects.get(pk=listing_id)
    try:
        Watchlist.objects.filter(user_id=request.user, listing_id = listing_id)[0]
        watchlist = True
    except:
        watchlist = False
    if listing.seller == request.user and not listing.closed:
        close = True
    else:
        close = False
    bid = Bids.objects.filter(listing_id=listing_id)
    bid = bid.aggregate(Max('bid'))
    winner = Bids.objects.get(listing_id=listing_id, bid=bid['bid__max'])
    if winner.user_id == request.user.id:
        won = True
    else:
        won = False
    comments = Comments.objects.filter(listing_id=listing_id)
    return render(request, "auctions/listing.html",{
        'listing': listing,
        'bid': currency(bid['bid__max']),
        'bidForm': BidForm(),
        'watchlist': watchlist,
        'close': close,
        'won': won,
        'comment': CommentForm(),
        'comments': comments
    })

@login_required(login_url='login')
def bid(request, listing_id):
    listing = Listings.objects.get(pk=listing_id)
    if request.method == 'POST':
        bform = BidForm(request.POST)
        if bform.is_valid():
            bid = bform.save(commit=False)
            bid.user = request.user
            bid.listing = Listings.objects.get(pk=listing_id)
            if bid.bid > Bids.objects.filter(listing_id=listing_id).aggregate(Max('bid'))['bid__max']:
                bid.save()
            else:
                try:
                    Watchlist.objects.filter(user_id=request.user, listing_id = listing_id)[0]
                    watchlist = True
                except:
                    watchlist = False
                listing = Listings.objects.get(pk=listing_id)
                bid = Bids.objects.filter(listing_id=listing_id)
                bid = bid.aggregate(Max('bid'))
                return render(request, "auctions/listing.html",{
                    'listing': listing,
                    'bid': currency(bid['bid__max']),
                    'bidForm': BidForm(),
                    'error': "Invalid Bid",
                    'watchlist': watchlist
                })
    return redirect(f'/listing/{listing_id}/{Listings.objects.get(pk = listing_id).title}')

@login_required(login_url='login')
def watchlist(request, listing_id=None):
    if request.method == 'POST':
        if not Watchlist.objects.filter(user_id=request.user, listing_id = listing_id):
            watchlist = Watchlist.objects.create(user_id=request.user, listing_id = Listings.objects.get(pk = listing_id))
            watchlist.save
        else:
            Watchlist.objects.get(user_id=request.user, listing_id = Listings.objects.get(pk = listing_id)).delete()
        return redirect(f'/listing/{listing_id}/{Listings.objects.get(pk = listing_id).title}')
    else:
        watchlist = Watchlist.objects.filter(user_id = request.user)
        print(f'Watchlist: {watchlist}', file=sys.stdout)
        return render(request, "auctions/watchlist.html", {
            'watchlist': watchlist
        })


@login_required(login_url='login')
def close(request, listing_id):
    listing = Listings.objects.get(pk=listing_id)
    if request.method == 'POST' and listing.seller == request.user:
        c = Listings.objects.get(pk=listing_id)
        c.closed = True
        c.save()   
    return redirect('index')

@login_required(login_url='login')
def comment(request, listing_id):
    if request.method == 'POST':
        listing = Listings.objects.get(pk=listing_id)
        if CommentForm(request.POST).is_valid():
            comment = CommentForm(request.POST).save(commit=False)
            comment.user_id = request.user
            comment.listing_id = listing
            comment.save()
            return redirect(f'/listing/{listing_id}/{Listings.objects.get(pk = listing_id).title}')

    else:
        return redirect(f'/listing/{listing_id}/{Listings.objects.get(pk = listing_id).title}')


def categories(request, category=None):
    if not category:
        categories = Listings.objects.all().values('category').distinct()
        print(f'Categories: {categories}', file=sys.stdout)
        return render(request, "auctions/categories.html", {
            'categories': categories
        })
    else:
        listings = Listings.objects.filter(category=category)
        return render(request, "auctions/categories.html", {
            'listings': listings
        })

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
<h1>Categories</h1>
{% if listings %}
<h2>{{listings.0.category}}</h2>
{% endif %}
<ul>
{% for category in categories %}
    {% if category.category %}
    <li><a href="categories/{{category.category}}">{{category.category}}</a></li>
    {% endif %}
{% endfor %}
</ul>
<div id="indexList">
    {% for listing in listings %}
        {% include "auctions/listingblock.html" %}
    {% endfor %}
    </div>
{% endblock %}

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}
{% block body %}
    <h1>Create Listing</h1>
    <form id="createForm" action="{% url 'create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %} 
        {{lform}}
        Bid:
        {{bform}}
        <input class="btn btn-primary" type="submit" value="Create page">
    </form>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>
    <div id="indexList">
    {% for listing in listings %}
        {% include "auctions/listingblock.html" %}
    {% endfor %}
    </div>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'categories' %}">Categories</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create' %}">Create Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}
{% block body %}
    {% if listing.category %}
    Category: <a href="{% url 'subCategories' listing.category %}">{{listing.category}}</a>
    {% endif %}
    <hr>
    <div id="listingTitleDiv">
        <h1>{{listing.title}}</h1>
        <span id="date">Created on {{listing.createDate}} by {{listing.seller}}</span>
    </div>
    <div id="listingMain">
        <div class="listingListingImg">
        {% if listing.imageImg %}
            <img class="listingImg" src="{{listing.imageImg.url}}" alt="Image listing">
        {% endif %}
        </div>
        <div id="listingMoney">
            <span id="listingBid">{{bid}}</span> 
            {% if not listing.closed %}
            {% if won %}
            <br>
            <span class="alert alert-primary">You are the highest bider!</span>
            {% endif %}
            <div id="listingForms">
                {% if error %}
                <span class="alert alert-danger" >{{error}}</span>
                {% endif %}
                <form id="bidForm" action="{% url 'bid' listing.id %}" method="POST">
                    {% csrf_token %}
                    {{bidForm}}
                    <input class="btn btn-primary" type="submit" value="Bid">
                </form>
                <form action="{% url 'watchlistAdd' listing.id %}" method="post">
                    {% csrf_token %}
                    {% if not watchlist %}
                        <input class="btn btn-secondary" type="submit" value="Add to watchlist">
                    {% else %}
                        <input class="btn btn-secondary" type="submit" value="Remove from watchlist">
                    {% endif %}
                </form>
            </div>
            {% endif %}
            {% if listing.closed %}
            <div class="alert alert-success">
            Listing closed.
                {% if won %}
                    You won!
                {% endif %}
            </div>
            {% endif %}
        </div> 
    </div>
    <div id="listingDescription">
    <b>Description:</b> <br>
    {{listing.description}}
    </div>
    <form action="{% url 'close' listing.id %}" method="post">
        {% csrf_token %}
        {% if close %}
            <input class="btn btn-danger" type="submit" value="Close">
        {% endif %}
    </form>
    <hr>
    <h2>Comments:</h2>
    <form action="{% url 'comment' listing.id %}" method="post">
        {% csrf_token %}
        {{comment}}
        <input class="btn btn-primary" type="submit" value="Comment">
    </form>
    <br>
    {% for comment in comments %}
    <div class="commentBlock">
        {{comment.user_id}}-<br>
        <span class="comment">{{comment.comment}}</span>
    </div>
    {% endfor %}
{% endblock %}

auctions/templates/auctions/listingblock.html
<div class="indexListing">
    <a href="{% url 'listing' listing.id listing.title %}">
        <div id="indexListingTitle">
            {{listing.title}}
        </div>
        <div class="indexListingImg" >
            {% if listing.imageImg %}
                <img class="indexListingImgImg"src="{{listing.imageImg.url}}" alt="Image listing">
            {% endif %}
        </div>
        <div id="indexDescription">
            {{listing.description}}   
        </div>
        <div id="indexPrice">
            €{{listing.bids_set.all.last.bid}} 
        </div>
    </a>
</div>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h1>Watchlist</h1>
    <div id="indexList">
        {% for listing in watchlist %}
            {% with listing=listing.listing_id %}             
                {% include "auctions/listingblock.html" %}
            {% endwith %}
        {% endfor %}
        </div>
{% endblock %}